# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-release
os: linux

env:
- CHECK=checkRawFiles FILE=fcs_sample_files BATCH=1
- CHECK=checkRawFiles FILE=fcs_sample_files BATCH=2
- CHECK=checkRawFiles FILE=fcs_sample_files BATCH=3
- CHECK=checkRawFiles FILE=fcs_control_files BATCH=1
- CHECK=checkRawFiles FILE=fcs_control_files BATCH=2
- CHECK=checkRawFiles FILE=fcs_control_files BATCH=3
- CHECK=checkStudyCompliance
- CHECK=checkPublicVsStudySchema
- CHECK=checkRawFiles FILE=protocols
- CHECK=checkRawFiles FILE=gene_expression_matrices
- CHECK=checkRawFiles FILE=gene_expression_files

jobs:
  include:
    - stage: load_dependencies
      script: Rscript warmup.R
    - stage: test
      script: travis_wait 40 Rscript check.R

notifications:
  email: false
  slack:
    rooms:
    - secure: ZUnlNXqERGzGHlbGJsM1UNgBh+X7YDhDH10ihqm9+d78Ak/fp6Yz+3d3bx3WuLOrX06oHOeYbc8mSeuEs3jUul1CHROY8l+xZoxiO6GgxONsTW5IEBlQZ/VIPK5AK0qvfBomQRSptWm3EGyd+ZcPdUOaYitg+jXCvop/TOea11hq0CynkF8Cme/DTC2opHYSjc8+9K36WRgnSh/1wnr3pAmdCAPQ/nLIR+yzU3kUdholPbuZrqUKoq+HANwvtNO90ogQXUn7KFv0eC3xz1TsJxUyAJ+ofralqImtRgZVokILCDr8tn7dQw356b0m0wZ4tvuE+UsY/wQhQB9tMwnGVjyFlHdPSDDYb71cZ3knUg1W1gTvjqi+i7i1SMO/9BUOyEqYt4/P0+zbt+LZxIHH2EMFjx1ayl5IA7IqJBvxm6V81efoyeOlSZpdWX+S63l1PsAU4pugbdzwP7XHDSSi19QHD8PSihWpqHckZOC8MSvIsETce6Woy6ZDHXhvKzvlG6H/xpRPddYWeioLwYY29tUXWw59zGqzoS0wJKim2jZYXZxrotWJqRF6E3+hH9yNxO8hqo81ZonkH5DtIE0bwCm1/n5EpABzoX/HLaXr3yNkvYZzFH6VQM6LoC3uaFlrK603Q9g4Lj/qEDo2/DEeCRF1bU8ZrSutKJIFV6y6EZ8=
    on_success: change # send a notification when the build status changes
    on_failure: always # always send a notification
